### ISSUE TITLE
v2.3 - Todo List [WIP]

### ISSUE THREAD

**Issue by qferr** [APY/APYDataGridBundle#801]
#### General

- [ ] #788 - Fix deprecated calls.
- [ ] #743 - Fix services with unresolved dependencies.
- [ ] #787 - Revise tests.

#### Grid

- [ ] #739 - Fix filters with undefined index error.

#### Mapping

- [ ] #773 #720 - Fix exception message for a missing source annotation.

#### Source

- [ ] #734 - Optimize number of queries.
- [ ] #417 - Add cache support for query result.
- [ ] #365 - Fix the total count when the GROUP BY statement is used.

#### Column

- [ ] #752 - Add a `translation_domain` property to options of column.
- [ ] #789 - Add a `empty_data` property to options of column.
- [ ] #243 - Add translation support for select options.
- [ ] #786 #648 - Add a `fetch_mode` property to options of column for change fetch mode in query.

#### Export

- [ ] #781 - Fix export array field shows empty.

#### Template

- [ ] #395 - Fix external filters when ajax requests reloads the template.

#### Documentation

- [ ] #778 - Fix usage of array column.
- [ ] #776 - Fix YAML configuration.
- [ ] #773 - Fix Annotation configuration.
- [ ] #721 - Fix README.
- [ ] #288 - Fix usage of multiple Grids on the same page.
- [ ] #287 - Fix required attributes for vector source.
- [ ] #249 - Add a note for usage another primary field.

**Comment by hmert** [comment]
Awesome! Have you check #121?

**Comment by qferr** [comment]
@hmert This todo list is in progress. 

@APY/collaborators Do not hesitate to add tasks.

**Comment by hmert** [comment]
@APY/collaborators hey everyone, let's release *2.3* and after *3.0 with sf3* and 💣  BC.

**Comment by Fidesio-Thomas** [comment]
Hi @qferr ,

Do you have a date planification for #143 & #829 ?

Thomas
